language: java
jdk:
- oraclejdk8
before_install:
- export | grep SAUCE_
script: make run_all_in_parallel
env:
  global:
  - BUILD_TAG=$TRAVIS_REPO_SLUG+$TRAVIS_BUILD_NUMBER
  - secure: Q1e0/LO8wRMVgi3YC+AJ4LMyTSlt9HyaDiSYF0aaEbNWWVh+P4e0OZdgiaauU1KH1KazJ5t3J19+3i8MXBSg68f8h8+zby2ocgwbz02zijruDkwnP0QTtJuMOkgknKX/5LEopx7m1v899nFe4dCz1a60HFik7BU9aLqsUk4bzXableu1pJ3EJ6fKYmKlP/M2cV5xIdUli0z5dPIR97r/BQX5ZR5+29NVTxEnxSTx2ydNwSSqEV5D3gUHs9oyQVVO1B2Ubg6sNFWgbyUvsdyvYRSVy+AWRW3Ihqa7+7TrMmqRwJNxlq5FSQ2GksBIWdYIwQ82zAnEmsLJhZ0Z/LTF4176/GqB2V6GwT4jTzjyF37347GwD6Fl2ZwJandNR0snbQw37DmlH+C1oFtKIY40s3YcMmD/DNexaTTy7z5+zPWyG6zhV2Z8A3TC/GL+Xu6p1+jf+X7t4WLdOt32LpRMk7u755GQgXNbFjUOM+5ImEd/HU8gWGlmZDjxNLGXshr/STOa+ZlHHuMNjwhQMKJXjj12QDhWXYqsuSHIDynMytUuSTnKAf4Y5/CTT0ze5sn3wEiNWvZ0tYzFi3URDH97hFPqi/tt6XZHRGRUqr+2LvVIgAXXxknwxgR24mi2/BkF/keNn9L3XgJMzDr+bfbuwsIxlon6ad2XdK5+rWp75FM=
  - secure: rJw/s12yINaUPJm/r3pkxReiCQN+UYnVgane0VwWkBbCI3LANba9IG1noJNaJiF7BJRo+onNKZPcByOxqHvYnawiIAl0pqHiI2EWuJApp+Qoeh/1S6WKF8GoYzIpSlvEKLxUjkSOmOuNSFwDq4QYuPnypWal8R17pxdDi/h8W8P7ByXtkkvXpulQw/XotvLDX11wO3uaniNMjR420rpG69yzB1mUBmNwvLL1jPrXKKVVg+1xJpm2fkiUiKVztKwVgni9fgSJk6JxoNHvgPZy2gZjsXJs2xisYCUC9QwWp8AxadYuO/6Px4dTih+shSyABd4ngYIOdUnwG9uoNdaqfgnyroMSSa3WfKzlMDDBfS0QMfeRByqnq3+Yc+cJiW16QkrdDGHqsjo6JhBKZ719a1PQI4ZoOhBdANEDpJ68dIen6azy5oZPVEsLtnwZGgQ9mwjYEtR9ugE6xxO2BHeRt8cv1/NMK44P4VfbTQBy7e2ZPhTpiZNqwSwhincAjHAByHz7f36uWJbG3yHL2KXp6HydM8aTUpyDHJNIEdLUJeeP9or+8ZXYiCtxmoQu0r4M/xWyqRSXNUjHXnIpi0i2vIcU1HnSeFe1F5oNXi+gRvAWnGCmjEK/cWmEJhDKY/CM8FDcw6ibFcDGmZBeQFqXdLBzA2Q3UW42qUFNE7+MPWI=
addons:
  sauce_connect: true
